import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from 'next/font/google'
import { Spectral } from 'next/font/google'
import localfont from "next/font/local";
import "./globals.css";
import { Noto_Serif } from 'next/font/google';

const notoSerif = Noto_Serif({
  weight: ['400', '700'], // Specify weights you need
  subsets: ['latin'], // Specify the subsets you need
  variable: "--font-notoSerif"
});
const ppNeueMontreal = localfont({
  src: [
    {
      path: "../fonts/PPNeueMontreal-Bold.otf",
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/PPNeueMontreal-Book.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/PPNeueMontreal-Italic.otf',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-ppneuemonteal', // Optional: Define a CSS variable for Tailwind integration
});

const inter = Inter({ subsets: ["latin"] });

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"], // Specify all weights you want to include
  style: ["normal", "italic"], // Include italic
  variable: "--font-spectral"
});

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ppNeueMontreal.className} ${notoSerif.variable} ${spectral.variable} text-primary-foreground`}>{children}</body>
    </html>
  );
}
